name: Rulebook-AI CI

on:
  push:
    branches: [ main, modernize-python-toolchain ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Set up uv
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Create virtual environment
        run: uv venv
      
      - name: Install dependencies
        run: |
          uv pip install -e ".[dev]"
          uv pip install pre-commit
      
      - name: Lint with pre-commit
        run: |
          pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Set up uv
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Create virtual environment
        run: uv venv
      
      - name: Install dependencies
        run: |
          uv pip install -e ".[dev]"
      
      - name: Run basic functionality test
        run: |
          rulebook-ai --help
          rulebook-ai list-rules
          mkdir -p test_project
          rulebook-ai install --rule-set light-spec --project-dir test_project
          rulebook-ai clean-all --project-dir test_project

      - name: Run tests with pytest
        run: uv run pytest --cov=rulebook_ai

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/modernize-python-toolchain')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Set up uv
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Create virtual environment
        run: uv venv
      
      - name: Install dependencies
        run: |
          uv pip install build
      
      - name: Build package
        run: |
          python -m build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/
